// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApplication.Models;

namespace TodoApplication.Data.Migrations
{
    [DbContext(typeof(TodoApplicationContext))]
    partial class TodoApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("TodoApplication.Models.Todo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AssignmentDate");

                    b.Property<string>("Category");

                    b.Property<string>("Content");

                    b.Property<long>("CreateDate")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
