// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApplication.Data;

namespace TodoApplication.Data.Migrations
{
    [DbContext(typeof(TodoApplicationContext))]
    partial class TodoApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("TodoApplication.Models.Todo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CatID");

                    b.Property<bool>("Complete");

                    b.Property<long>("CreateDate")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Name");

                    b.Property<long>("UpdateDate");

                    b.HasKey("ID");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("TodoApplication.Models.TodoCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreatedDay");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("TodoCategory");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDay = 0L,
                            Name = "Work"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDay = 0L,
                            Name = "Home"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDay = 0L,
                            Name = "Personal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
